name: Go

on: [push]

jobs:
  test:
    name: Check code quality and run tests
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Get all dependencies
      run: go get -u ./...

    - name: Format
      run: diff -u <(echo -n) <(gofmt -d ./)

    - name: Suspicious constructs
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
